development: &default
  adapter: postgresql
  database: BookingRGV_development
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  username: master
  password: <%= ENV['BOOKINGRGV_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5434

test:
  <<: *default
  database: BookingRGV_test
  username: postgres
  host: localhost

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
